### ISSUE TITLE
Stuck at ego gift 

### ISSUE THREAD

**Issue by SrCobayo** [Samsterr/sir-squirrel-assistant#31] opened 2024-10-23 14:50 UTC
It's the third time that it gets stuck when receiving a burn ego gift i don't remember if it's always the same one this time es is "pinpoint logic circuit"

Log:
2024-10-23 04:13:39,308 - __main__ - INFO - Run 2
2024-10-23 04:13:39,530 - src.core - INFO - Converting Enkephalin to Modules
2024-10-23 04:13:45,479 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-23 04:13:49,922 - __main__ - INFO - Current Team: charge
2024-10-23 04:13:54,697 - src.mirror - INFO - E.G.O Gift Selection
2024-10-23 04:13:59,435 - src.mirror - INFO - Mirror Dungeon Squad Select
2024-10-23 04:14:06,490 - src.core - INFO - Loading
2024-10-23 04:14:11,692 - src.mirror - INFO - Selecting Pack
2024-10-23 04:14:12,542 - src.mirror - DEBUG - Current Floor f1
2024-10-23 04:14:12,785 - src.mirror - DEBUG - 47.333333333333336
2024-10-23 04:14:12,996 - src.mirror - DEBUG - pack exclusion not detected, status detceted, choosing from status
2024-10-23 04:14:14,437 - src.core - INFO - Moving to Next Floor
2024-10-23 04:14:19,626 - src.mirror - INFO - Navigating
2024-10-23 04:14:26,606 - src.mirror - INFO - Selecting Squad for Battle
2024-10-23 04:14:33,225 - src.core - INFO - Loading
2024-10-23 04:14:42,544 - src.core - INFO - Starting Battle
2024-10-23 04:15:28,797 - src.core - INFO - Loading
2024-10-23 04:15:35,588 - src.mirror - INFO - Navigating
2024-10-23 04:15:40,214 - src.mirror - INFO - Entered ? node
2024-10-23 04:15:43,738 - src.mirror - INFO - Event
2024-10-23 04:15:44,098 - src.mirror - DEBUG - Select to gain EGO Gift
2024-10-23 04:15:51,054 - src.mirror - DEBUG - KQE

**Comment by SrCobayo** [comment] 2024-10-23 14:51
![image](https://github.com/user-attachments/assets/2d84c0b6-ea40-426f-b844-1967e3047524)

**Comment by Samsterr** [comment] 2024-10-23 14:58
Hi, is the issue related to freezing at the navigation but theres the EGO GIFT GET prompt blocking the screen?
![375929913-609cfd2e-2329-4fc1-afc7-cef38a08490d](https://github.com/user-attachments/assets/4d0f7236-2838-46cd-8e78-685ba63f1ec9)
Something like this?

**Comment by SrCobayo** [comment] 2024-10-24 21:02
Yes. and yes i've the hotfix.

**Comment by Samsterr** [comment] 2024-10-25 02:09
@SrCobayo can you use this debug version at the bottom which should help me diagnose the issue should you run into it again. Can i check if its only for that specific EGO gift?
[sirsquirrel.zip](https://github.com/user-attachments/files/17514706/sirsquirrel.zip)

**Comment by SrCobayo** [comment] 2024-10-25 04:50
That zip is being tagged as an wacatac trojan lol

**Comment by Samsterr** [comment] 2024-10-25 08:27
Does the original version get flagged? The only changes i made was to add some debug prints for the squirrel.log?

**Comment by Samsterr** [comment] 2024-10-25 08:33
@SrCobayo ive looked into it and sometimes pyinstaller which is what i use to convert the python program to exe gets sometimes detected as trojan. You can also use a pyinstaller extractor to view the source yourself  if you do not trust the program.

**Comment by SrCobayo** [comment] 2024-10-25 16:09
The original releases do not get flagged by windows antivirus, i tested the launchers (original and hotfix) on virus total and they have the same results, kinda weird.

**Comment by Samsterr** [comment] 2024-10-25 19:51
pyinstallers own issue tracking here : https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virustotal+is%3Aclosed speaks about the issue as well seemingly related to their precompiled binaries

**Comment by SrCobayo** [comment] 2024-10-26 06:54
![image](https://github.com/user-attachments/assets/c7e60fc2-a513-419f-814e-44daf80a68b7)
2024-10-26 03:43:15,137 - __main__ - INFO - Starting Run
2024-10-26 03:43:15,138 - __main__ - INFO - Run 1
2024-10-26 03:43:15,381 - src.core - INFO - Converting Enkephalin to Modules
2024-10-26 03:43:21,464 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-26 03:43:24,674 - __main__ - INFO - Current Team: charge
2024-10-26 03:43:48,268 - src.mirror - INFO - Resuming Run
2024-10-26 03:43:50,478 - src.core - INFO - Loading
2024-10-26 03:43:57,548 - src.mirror - INFO - Navigating
2024-10-26 03:44:03,629 - src.mirror - INFO - Selecting Squad for Battle
2024-10-26 03:44:25,832 - src.core - INFO - Starting Battle
2024-10-26 03:45:14,473 - src.core - INFO - Loading
2024-10-26 03:45:21,483 - src.mirror - INFO - Navigating
2024-10-26 03:45:28,888 - src.mirror - INFO - Selecting Squad for Battle
2024-10-26 03:45:44,244 - src.core - INFO - Starting Battle
2024-10-26 03:46:34,741 - src.core - INFO - Loading
2024-10-26 03:46:41,725 - src.mirror - INFO - Navigating
2024-10-26 03:46:52,932 - src.mirror - INFO - Selecting Squad for Battle
2024-10-26 03:47:08,085 - src.core - INFO - Starting Battle
2024-10-26 03:48:57,029 - src.core - INFO - Battle Event Check
2024-10-26 03:48:58,815 - src.core - DEBUG - PINK SHOES
2024-10-26 03:49:02,198 - src.core - INFO - Skill Check
2024-10-26 03:49:50,004 - src.core - INFO - Loading
2024-10-26 03:49:54,205 - src.mirror - INFO - Reward Selection
2024-10-26 03:50:02,537 - src.mirror - INFO - Encounter Reward Selection
2024-10-26 03:50:13,273 - src.mirror - INFO - Selecting Pack
2024-10-26 03:50:14,107 - src.mirror - DEBUG - Current Floor f3
2024-10-26 03:50:14,339 - src.mirror - DEBUG - 47.333333333333336
2024-10-26 03:50:16,964 - src.mirror - DEBUG - PACKS: pack exclusion detected, refreshing
2024-10-26 03:50:18,543 - src.mirror - INFO - Selecting Pack
2024-10-26 03:50:19,377 - src.mirror - DEBUG - Current Floor f3
2024-10-26 03:50:19,605 - src.mirror - DEBUG - 12.666666666666666
2024-10-26 03:50:23,563 - src.mirror - DEBUG - pack exclusion not detected, status detceted, choosing from status
2024-10-26 03:50:24,999 - src.core - INFO - Moving to Next Floor
2024-10-26 03:50:34,325 - src.mirror - INFO - Navigating
2024-10-26 03:50:39,033 - src.mirror - INFO - Entered ? node
2024-10-26 03:50:42,901 - src.mirror - INFO - Rest Stop
2024-10-26 03:50:45,078 - src.mirror - DEBUG - 22.333333333333332
2024-10-26 03:50:47,214 - src.mirror - DEBUG - REST STOP: HEALING ALL SINNERS
2024-10-26 03:50:50,236 - src.mirror - DEBUG - REST STOP: ENHANCING EGO GIFTS
2024-10-26 03:50:51,631 - src.mirror - DEBUG - DEBUG: Found Status GIFT
2024-10-26 03:50:51,843 - src.mirror - DEBUG - 55.666666666666664
2024-10-26 03:50:54,111 - src.mirror - DEBUG - REST STOP: EGO STATUS GIFT UPGRADED
2024-10-26 03:50:57,819 - src.mirror - DEBUG - REST STOP: EGO STATUS GIFT UPGRADED
2024-10-26 03:50:59,463 - src.mirror - DEBUG - 35.333333333333336
2024-10-26 03:50:59,842 - src.mirror - DEBUG - 14.333333333333334
2024-10-26 03:50:59,923 - src.mirror - DEBUG - 55.666666666666664
2024-10-26 03:51:02,176 - src.mirror - DEBUG - REST STOP: EGO STATUS GIFT UPGRADED
2024-10-26 03:51:05,615 - src.mirror - DEBUG - REST STOP: NOT ENOUGH COST, EXITING ENHANCE PAGE
2024-10-26 03:51:11,745 - src.mirror - DEBUG - DEBUG: Finished Enhancing
2024-10-26 03:51:18,110 - src.mirror - INFO - Navigating
2024-10-26 03:51:22,830 - src.mirror - INFO - Entered ? node
2024-10-26 03:51:26,369 - src.mirror - INFO - Event
2024-10-26 03:51:26,946 - src.mirror - DEBUG - Pass to gain EGO Gift
2024-10-26 03:51:30,235 - src.core - INFO - Skill Check

**Comment by Samsterr** [comment] 2024-10-26 07:18
@SrCobayo i cant seem to replicate your issue even with a low spec laptop to account for any loading discrepancy. I have also counter checked the functions against your attached screenshot and it has no issue detecting the elements as well. please grab the latest release and this debug exe so i can check what is the issue as this should not be an issue as of hotfix 2
[sirsquirrel.zip](https://github.com/user-attachments/files/17529428/sirsquirrel.zip)

**Comment by SrCobayo** [comment] 2024-10-30 03:57
2024-10-30 00:05:11,724 - __main__ - INFO - Starting Run
2024-10-30 00:05:11,724 - __main__ - INFO - Run 1
2024-10-30 00:05:12,203 - src.core - INFO - Converting Enkephalin to Modules
2024-10-30 00:05:19,228 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-30 00:05:23,073 - __main__ - INFO - Current Team: charge
2024-10-30 00:05:43,514 - __main__ - INFO - Starting Run
2024-10-30 00:05:43,514 - __main__ - INFO - Run 1
2024-10-30 00:05:43,913 - src.core - INFO - Converting Enkephalin to Modules
2024-10-30 00:05:50,888 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-30 00:05:56,115 - __main__ - INFO - Current Team: charge
2024-10-30 00:06:00,022 - src.mirror - INFO - Resuming Run
2024-10-30 00:06:02,377 - src.core - INFO - Loading
2024-10-30 00:06:11,108 - src.mirror - INFO - Navigating
2024-10-30 00:06:22,095 - src.mirror - INFO - Selecting Squad for Battle
2024-10-30 00:06:42,567 - src.core - INFO - Starting Battle
2024-10-30 00:07:07,900 - src.core - INFO - Loading
2024-10-30 00:07:13,600 - src.mirror - INFO - Encounter Reward Selection
2024-10-30 00:07:27,851 - src.mirror - INFO - Navigating
2024-10-30 00:07:38,781 - src.mirror - INFO - Selecting Squad for Battle
2024-10-30 00:07:53,771 - src.core - INFO - Starting Battle
2024-10-30 00:08:37,118 - src.core - INFO - Loading
2024-10-30 00:08:47,459 - src.mirror - INFO - Navigating
2024-10-30 00:08:56,369 - src.mirror - INFO - Entered ? node
2024-10-30 00:09:02,439 - src.mirror - INFO - Event
2024-10-30 00:09:03,413 - src.mirror - DEBUG - Pass to gain EGO Gift
2024-10-30 00:09:07,403 - src.core - INFO - Skill Check

![image](https://github.com/user-attachments/assets/fb230563-249c-4ef0-8943-a6fb1b9c7c70)

**Comment by Samsterr** [comment] 2024-10-30 04:14
Whats resolution and scale are you running limbus

**Comment by Samsterr** [comment] 2024-11-02 11:28
closing, not reproducible

**Comment by Sannann** [comment] 2024-11-02 23:46
Happens to me all the time. 1920x1080, I believe happens both on borderless and windowed, will gladly replicate it.

**Comment by Sannann** [comment] 2024-11-03 00:01
I apolgoize, I do not know what part of the log is relevant:

2024-11-02 20:58:03,153 - src.mirror - DEBUG - REST STOP: EGO STATUS GIFT UPGRADED
2024-11-02 20:58:06,498 - src.mirror - DEBUG - REST STOP: NOT ENOUGH COST, EXITING ENHANCE PAGE
2024-11-02 20:58:18,538 - src.mirror - INFO - Navigating
2024-11-02 20:58:23,148 - src.mirror - INFO - Entered ? node
2024-11-02 20:58:26,577 - src.mirror - INFO - Event
2024-11-02 20:58:27,214 - src.mirror - DEBUG - Pass to gain EGO Gift
2024-11-02 20:58:30,502 - src.core - INFO - Skill Check

It gets stuck afterwards, does nothing. This happened in borderless. Restarting the program worked. Will replicate again if asked/send another example if I get one

![image](https://github.com/user-attachments/assets/1c06cf88-43a9-4f06-a328-c988ebd213f9)

**Comment by Samsterr** [comment] 2024-11-03 09:33
i suspect this issue is related to something during the skill check function but i will need to add more debugs to identify what the issue is and upload it here later

**Comment by Samsterr** [comment] 2024-11-09 02:06
@Sannann let me know if u still encounter this issue on the latest release

**Closed** 2024-11-20 15:29 UTC
