### ISSUE TITLE
[Inconsistent] Battle Events not proceeding properly

### ISSUE THREAD

**Issue by Samsterr** [Samsterr/sir-squirrel-assistant#18] opened 2024-10-11 09:54 UTC
Need more feedback regarding this. I have a temporary fixed but would like to know if it still gets stuck

**Comment by 72kadi** [comment] 2024-10-12 05:16
Hello!
Thanks for sharing your work!

Feedback about events. 
Stucked in:
Events where you do not get a reward but need to roll.
Or* it is in events where you're not sent to roll right away but need to tap Proceed button before be sending to roll.

Examples of  certain events:
- Drifting Fox
- Paper Chairman

Will attach SSs at what point it getting stuck. (1st SS)
And what i mean by "Rolling with unit" = window of that process. Yet again. Bot doing it by itself no issues but can not proceed to that window by itself. (2nd SS)
After manual taping Proceed button = bot will proceed working with choosing person to roll with and go forth.

![Drifting fox event](https://github.com/user-attachments/assets/8f4b5241-e91f-4370-bb7a-097d0586e552)
![RollWindowSS](https://github.com/user-attachments/assets/b4dcdb33-ef12-413b-827d-b4e626f474da)

**Comment by 72kadi** [comment] 2024-10-12 06:01
2024-10-12 10:45:42,432 - src.mirror - INFO - Navigating
2024-10-12 10:45:46,843 - src.mirror - INFO - Entered ? node
2024-10-12 10:45:51,067 - src.mirror - INFO - Event
2024-10-12 10:45:51,389 - src.mirror - DEBUG - Select to gain EGO Gift

stucked on road map of MD on EGO Gift confirmation tab
![after event stuck](https://github.com/user-attachments/assets/609cfd2e-2329-4fc1-afc7-cef38a08490d)

**Comment by Samsterr** [comment] 2024-10-12 06:34
@72kadi can you test this hotfix to see if it resolves your issue.
[sirsquirrel.zip](https://github.com/user-attachments/files/17349067/sirsquirrel.zip)

**Comment by 72kadi** [comment] 2024-10-12 06:45
> @72kadi can you test this hotfix to see if it resolves your issue. [sirsquirrel.zip](https://github.com/user-attachments/files/17349067/sirsquirrel.zip)

i'll be able to run it in an hour.
will drop info if it'll stuck anywhere or not after few runs

**Comment by Samsterr** [comment] 2024-10-12 08:04
@72kadi please use the latest hotfix found under release instead as i identified another issue with the earlier zip sent here

**Comment by 72kadi** [comment] 2024-10-12 08:47
Not event but still

2024-10-12 13:43:25,737 - src.mirror - INFO - Loading
2024-10-12 13:43:34,292 - src.core - INFO - Starting Battle
2024-10-12 13:44:31,796 - src.core - INFO - Loading
2024-10-12 13:44:39,270 - src.mirror - INFO - Reward Selection
2024-10-12 13:44:46,907 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:44:56,948 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:45:04,246 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:45:11,502 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:45:18,872 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:45:26,279 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:45:40,481 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:45:47,999 - src.mirror - INFO - Encounter Reward Selection

Stucked at EGO Gift 
![stucked after encounter reward drop](https://github.com/user-attachments/assets/f075b555-14b5-4e31-a9f1-d845fa34e9fd)

**Comment by 72kadi** [comment] 2024-10-12 08:52
Not event again

2024-10-12 13:45:47,999 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 13:47:02,662 - src.mirror - INFO - Selecting Pack
2024-10-12 13:47:03,405 - src.mirror - DEBUG - Current Floor f3
2024-10-12 13:47:03,604 - src.mirror - DEBUG - 69.33333333333333
2024-10-12 13:47:05,692 - src.mirror - DEBUG - PACKS: pack exclusion detected, status detected, refreshing
2024-10-12 13:47:07,153 - src.mirror - INFO - Selecting Pack
2024-10-12 13:47:07,886 - src.mirror - DEBUG - Current Floor f3
2024-10-12 13:48:11,021 - __main__ - INFO - Starting Run
2024-10-12 13:48:11,021 - __main__ - INFO - Run 1
2024-10-12 13:48:11,234 - src.core - INFO - Converting Enkephalin to Modules
2024-10-12 13:48:11,967 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-12 13:48:12,504 - __main__ - INFO - Current Team: sinking
2024-10-12 13:48:14,270 - src.mirror - INFO - Selecting Pack
2024-10-12 13:48:15,003 - src.mirror - DEBUG - Current Floor f3
2024-10-12 13:48:15,201 - src.mirror - DEBUG - 18.666666666666668
2024-10-12 13:48:15,757 - src.mirror - DEBUG - PACKS: pack exclusion detected, refreshing
2024-10-12 13:48:17,318 - src.mirror - INFO - Selecting Pack


It stoped working at Pack Selection.
After re-starting it = loop of trying to refresh the packs.

ig just need to add more packs into configs .txt files manually

SS from cmd
![PACK SELECTION STUCK](https://github.com/user-attachments/assets/abd39f3e-2def-4811-bf8f-1fd2cb0088e8)

**Comment by Samsterr** [comment] 2024-10-12 10:23
@72kadi  can i check what windows display scale you are on and at what resolution is your monitor as well as the game

**Comment by 72kadi** [comment] 2024-10-12 21:03
> @72kadi can i check what windows display scale you are on and at what resolution is your monitor as well as the game

1920x1080 both
![LC Resolutiuon](https://github.com/user-attachments/assets/c06393cb-393e-439b-9a12-d117b750516a)

![PC Reso=lurtion](https://github.com/user-attachments/assets/8666ff28-d0dc-45c3-b12d-bd97cd7a9876)


But prolly the game doesn't care about what is set and it force resolution of its own.
will try on my 2nd monitor

**Comment by Samsterr** [comment] 2024-10-12 21:14
If im not mistakened the bot should not work in the second monitor and only the primary one. I have tested on a 1080p screen on my end and cant seem to replicate your issue but based off the logs it seems to be slightly off scale due to the value its reporting back during pack selection. Could you try using windowed mode as shown in the instructions and see if it solves your issue.

**Comment by 72kadi** [comment] 2024-10-12 23:15
2024-10-13 04:06:11,977 - src.mirror - INFO - Navigating
2024-10-13 04:06:18,532 - src.mirror - INFO - Selecting Squad for Battle
2024-10-13 04:06:25,036 - src.mirror - INFO - Loading
2024-10-13 04:06:33,523 - src.core - INFO - Starting Battle
2024-10-13 04:07:36,689 - src.core - INFO - Loading
2024-10-13 04:07:40,824 - src.mirror - INFO - Reward Selection
2024-10-13 04:07:48,415 - src.mirror - INFO - Encounter Reward Selection
2024-10-13 04:07:58,182 - src.mirror - INFO - Encounter Reward Selection
2024-10-13 04:08:05,423 - src.mirror - INFO - Encounter Reward Selection
2024-10-13 04:08:12,655 - src.mirror - INFO - Encounter Reward Selection
2024-10-13 04:08:19,902 - src.mirror - INFO - Encounter Reward Selection
2024-10-13 04:08:27,172 - src.mirror - INFO - Encounter Reward Selection
2024-10-13 04:08:34,477 - src.mirror - INFO - Encounter Reward Selection
2024-10-13 04:08:41,736 - src.mirror - INFO - Encounter Reward Selection

![01stucked after encounter reward drop](https://github.com/user-attachments/assets/4ef56b5d-f590-4a39-8735-92bff888904d)

2024-10-12 14:59:01,427 - src.mirror - INFO - Navigating
2024-10-12 14:59:07,962 - src.mirror - INFO - Selecting Squad for Battle
2024-10-12 14:59:14,488 - src.mirror - INFO - Loading
2024-10-12 14:59:23,055 - src.core - INFO - Starting Battle
2024-10-12 15:00:17,138 - src.core - INFO - Loading
2024-10-12 15:00:24,821 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:00:34,670 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:00:42,003 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:00:49,283 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:00:56,620 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:01:03,951 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:01:11,270 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:01:18,587 - src.mirror - INFO - Encounter Reward Selection
2024-10-12 15:01:25,902 - src.mirror - INFO - Encounter Reward Selection

![2nd time stucked](https://github.com/user-attachments/assets/b8800900-aaee-40a1-86aa-4fa477e5b7f2)


testing it on 2nd display. Same stuck-loop after encounter rewards.
From what i understood = these EGO Gifts are from 33% chance picks. where you *can* get ego gift.
and when you do get = bot get stucked.

**Comment by 72kadi** [comment] 2024-10-12 23:17
> If im not mistakened the bot should not work in the second monitor and only the primary one. I have tested on a 1080p screen on my end and cant seem to replicate your issue but based off the logs it seems to be slightly off scale due to the value its reporting back during pack selection. Could you try using windowed mode as shown in the instructions and see if it solves your issue.

yeah. it doesn't work on 2ndry display.
what i meant = testing on 2nd monitor as prime one.
since one monitor bigger and in Display settings 1080 is recommended one.
while another = manually picked 1080 (did all tests before on smaller one)

but ig it wouldn't work if scale was off.
i've tried on my old laptop just to see if can play it there. display can not go up to 1080 in settings = bot didn't work at all

**Comment by 72kadi** [comment] 2024-10-12 23:22
ig i was lucky to not get 33% EGO Gifts in x2 runs = since bot worked properly w\o any roadblocks.
just the one thing = it stucked at the end of MD. When shown that you accepted rewards = shoowing battlepass lvl got = waiting for confirm button click.

Yet even after manual clicking bot will not go as usual before you go to Mirror Dungeon screen manually.

talking about setting bot to run several dungeons and not just 1 round.

Will drop SS after this run if it'll be stucked again

**Comment by 72kadi** [comment] 2024-10-12 23:44
Skip-spam stuck in event node

2024-10-13 04:41:15,965 - src.mirror - INFO - Navigating
2024-10-13 04:41:20,377 - src.mirror - INFO - Entered ? node
2024-10-13 04:41:24,684 - src.mirror - INFO - Event
2024-10-13 04:41:25,023 - src.mirror - DEBUG - Select to gain EGO Gift

![02 Spam Skip Stuck](https://github.com/user-attachments/assets/8ded1f16-8999-4198-b958-42eab548ef33)

**Comment by Samsterr** [comment] 2024-10-13 00:24
kqe event is handled by the new 0.8.4 release

**Comment by Samsterr** [comment] 2024-10-13 02:24
> 2024-10-13 04:06:11,977 - src.mirror - INFO - Navigating 2024-10-13 04:06:18,532 - src.mirror - INFO - Selecting Squad for Battle 2024-10-13 04:06:25,036 - src.mirror - INFO - Loading 2024-10-13 04:06:33,523 - src.core - INFO - Starting Battle 2024-10-13 04:07:36,689 - src.core - INFO - Loading 2024-10-13 04:07:40,824 - src.mirror - INFO - Reward Selection 2024-10-13 04:07:48,415 - src.mirror - INFO - Encounter Reward Selection 2024-10-13 04:07:58,182 - src.mirror - INFO - Encounter Reward Selection 2024-10-13 04:08:05,423 - src.mirror - INFO - Encounter Reward Selection 2024-10-13 04:08:12,655 - src.mirror - INFO - Encounter Reward Selection 2024-10-13 04:08:19,902 - src.mirror - INFO - Encounter Reward Selection 2024-10-13 04:08:27,172 - src.mirror - INFO - Encounter Reward Selection 2024-10-13 04:08:34,477 - src.mirror - INFO - Encounter Reward Selection 2024-10-13 04:08:41,736 - src.mirror - INFO - Encounter Reward Selection
> 
> ![01stucked after encounter reward drop](https://private-user-images.githubusercontent.com/184717833/375992400-4ef56b5d-f590-4a39-8735-92bff888904d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODU3MjksIm5iZiI6MTcyODc4NTQyOSwicGF0aCI6Ii8xODQ3MTc4MzMvMzc1OTkyNDAwLTRlZjU2YjVkLWY1OTAtNGEzOS04NzM1LTkyYmZmODg4OTA0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwMjEwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjM5MTJiYzMzMDEzNWUwMmY4ZjQ5Y2I5OWUzY2JmNTYxYmE1NzRjMzBlNTgxZTg0MzY4Nzk2ZDIwM2MxY2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XKJnBrlgoQLUTJuklHp2YpvHQ-VmKTgqOky_ucbGshE)
> 
> 2024-10-12 14:59:01,427 - src.mirror - INFO - Navigating 2024-10-12 14:59:07,962 - src.mirror - INFO - Selecting Squad for Battle 2024-10-12 14:59:14,488 - src.mirror - INFO - Loading 2024-10-12 14:59:23,055 - src.core - INFO - Starting Battle 2024-10-12 15:00:17,138 - src.core - INFO - Loading 2024-10-12 15:00:24,821 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:00:34,670 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:00:42,003 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:00:49,283 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:00:56,620 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:01:03,951 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:01:11,270 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:01:18,587 - src.mirror - INFO - Encounter Reward Selection 2024-10-12 15:01:25,902 - src.mirror - INFO - Encounter Reward Selection
> 
> ![2nd time stucked](https://private-user-images.githubusercontent.com/184717833/375992422-b8800900-aaee-40a1-86aa-4fa477e5b7f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODU3MjksIm5iZiI6MTcyODc4NTQyOSwicGF0aCI6Ii8xODQ3MTc4MzMvMzc1OTkyNDIyLWI4ODAwOTAwLWFhZWUtNDBhMS04NmFhLTRmYTQ3N2U1YjdmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwMjEwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODJkNTBhOWUyMmE5ODZjOTY1MDNhZjIyN2E3YmQ5ZDY2MDE0MjQxZWY4MjZkN2JkMGNkNmE2MzA5NmQwYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dPmrGCAWgEUrYfCx57lvAYN9uoTVTY3CERhWc7-lrpU)
> 
> testing it on 2nd display. Same stuck-loop after encounter rewards. From what i understood = these EGO Gifts are from 33% chance picks. where you _can_ get ego gift. and when you do get = bot get stucked.

this is already handled by the bot and i cant seem to replicate your issue on my end

**Comment by 72kadi** [comment] 2024-10-14 05:05
Greetings.
Thanks for your work yet again!

sharing single issue i meet a lot.
inconsisten repeated runs.
if you have any ideas why it can be so

2024-10-14 10:00:32,566 - src.mirror - INFO - Run Won
2024-10-14 10:00:37,862 - src.mirror - INFO - Rewards Claimed
2024-10-14 10:00:41,586 - __main__ - INFO - Run 2
2024-10-14 10:00:41,786 - src.core - INFO - Converting Enkephalin to Modules
2024-10-14 10:00:42,495 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-14 10:00:43,004 - __main__ - INFO - Current Team: sinking

most of the times it get stucked at this screen and will not proceed till going manually to mirror dungeon screen.
sometimes it proceed with several runs in a row.

![pass level stuck](https://github.com/user-attachments/assets/2fb29f47-7f13-491a-a4df-f7183883e948)

**Comment by Samsterr** [comment] 2024-10-14 05:14
@72kadi can i check are you using the latest release?

**Comment by 72kadi** [comment] 2024-10-14 05:25
> @72kadi can i check are you using the latest release as i have put out a few hotfixes recently

Downloaded both 0.84 hot fix + .exe file less than hour ago.

Also wanted to mention. For some reason it doesn't pick team at the start of the MD run.

I've Edited config  .txt to have only "sinking".
.json still have every status team + default.
Chose the name of a team from tag.

Yet started it = on team selection screen it was on a random one = bot started the run with that selected team.
If manually set the right team (as "main one". So it will be selected before start of MD) with the right name = bot will use info team selection from .json as intended.

So the issue that bot didn't select the team befor starting the run but ran with one which were selected

**Comment by Samsterr** [comment] 2024-10-14 05:39
@72kadi  can you upload your squirrel.log here

**Comment by 72kadi** [comment] 2024-10-14 05:57
about team selection issue.

logs:
2024-10-14 10:49:44,742 - __main__ - INFO - Starting Run
2024-10-14 10:49:44,742 - __main__ - INFO - Run 1
2024-10-14 10:49:44,940 - src.core - INFO - Converting Enkephalin to Modules
2024-10-14 10:49:50,812 - src.core - INFO - Navigating to Mirror Dungeon
2024-10-14 10:49:55,146 - __main__ - INFO - Current Team: sinking
2024-10-14 10:49:59,615 - src.mirror - INFO - E.G.O Gift Selection
2024-10-14 10:50:04,240 - src.mirror - INFO - Mirror Dungeon Squad Select
2024-10-14 10:50:09,997 - src.mirror - INFO - Loading
2024-10-14 10:50:15,162 - src.mirror - INFO - Selecting Pack
2024-10-14 10:50:15,910 - src.mirror - DEBUG - Current Floor f1
2024-10-14 10:50:16,122 - src.mirror - DEBUG - 47.333333333333336
2024-10-14 10:50:16,316 - src.mirror - DEBUG - pack exclusion not detected, choosing from status
2024-10-14 10:50:17,763 - src.mirror - INFO - Moving to Next Floor
2024-10-14 10:50:22,961 - src.mirror - INFO - Navigating
2024-10-14 10:50:29,603 - src.mirror - INFO - Selecting Squad for Battle

it starts the run with whatever team it is picked. yet it is kind of "Searching" for the team before start.
but doesn't pick sinking (in that example) at proceed to the run
![image](https://github.com/user-attachments/assets/0b2b3c37-c237-4c98-9209-229e25799ac0)

team #1 is selected and bot will proceed with it
Team "sinking" is name from the tag as by instruction -> bot doesn't pick this team by itself.

in config files team seted as "sinking" -> so it will team formation from .json for sinkin.

so the thing is.
- bot started the run w/o choosing the "right team" for sinking. But with the one were picked before.
- bot used .json battle formation of *sinking* since that's what set in type-config file. 
And **not** default formation from .json as if no type were selected

**Comment by Samsterr** [comment] 2024-10-14 06:19
@72kadi thanks for letting me know. i have added a short delay for the battle pass screen to see if it fixes your issue as i noted that it doesn't detect the loading screen that occurs after you press confirm on the battle pass notification.  The issue with team picking is my fault for accidentally commenting out the function to click on the team due to another issue a user faced, thanks for informing me about the issue and download the updated hotfix in release

**Closed** 2024-10-18 08:34 UTC
